### ISSUE TITLE
Bela Mini Schematics in the future?

### ISSUE THREAD

**Issue by everythingwillbetakenaway** [BelaPlatform/bela-hardware#6]
Hello, 

Does Bela community planning to release hardware schematics of the Bela Mini Project?

**Comment by LBDonovan** [comment]
It's cleverly hidden in the incorrectly named `pocketbela-cape` directory in this repo:

https://github.com/BelaPlatform/bela-hardware/tree/master/pocketbela-cape/belamini_cape_rev_B2

**Comment by everythingwillbetakenaway** [comment]
Perfect!!
